### ISSUE TITLE
Docker version doesn't work

### ISSUE THREAD

**Issue by 0xd34b33f** [n1try/wakapi#10]
```
wakapi_db    | [services.d] done.
wakapi_db    | 191113 10:03:42 mysqld_safe Logging to syslog.
wakapi_db    | 191113 10:03:42 mysqld_safe Starting mysqld daemon with databases from /config/databases
wakapi       | Starting Application
wakapi       | 2019/11/13 10:03:53 Could not connect to database.
wakapi exited with code 1
```
Built it using default docker compose file on ubuntu 18.04

**Comment by n1try** [comment]
I guess I know what the problem is. Just recently, I updated the database configuration, but didn't adapt the Docker files. 
Try to add `WAKAPI_DB_PORT=3306` environment variable to the compose file and let me know if that fixes your issue. If yes, I'm going to push an update later that day.

**Comment by 0xd34b33f** [comment]
The most strange thing, that service works, if I run it on different host. I think, that problem is somewhere on my side

**Comment by n1try** [comment]
Ok, keep us posted if you managed to solve the problem.
I just tried it on my machine and everything seems to work for me.

**Comment by n1try** [comment]
@0xd34b33f Did you manage to solve it?
