### ISSUE TITLE
Real frontend

### ISSUE THREAD

**Issue by nemanjan00** [n1try/wakapi#11]
Hi, 

I have wanted wakatime for quite some time now. 

I do plan to write frontend for this app. 

Would you be ok with accepting Vue based frontend for it?

**Comment by n1try** [comment]
Hi @nemanjan00, 

thanks for having a take on this! I'm totally fine with Vue, it would probably have been my choice as well.
Concerning the frontend, I think of having some basic dashboard with certain graphs and statistics. But keep it minimalist. Personally, I like Material design, e.g. with the help of [Vuetify](https://vuetifyjs.com/en/), but I'll leave choice like that to you.

**Comment by nemanjan00** [comment]
I am not really familiar with Vuetify, I am more of an bootstrap-vue kind of a guy, but, I will learn Vuetify

**Comment by n1try** [comment]
Bootstrap is totally fine as well, especially if you already have experience with it.

**Comment by nemanjan00** [comment]
Thanks. Will probably work on it this weekend

**Comment by n1try** [comment]
Any progress yet? 😊

**Comment by nemanjan00** [comment]
Hi. 

I was unable to do much last weekend... 

Do you want to keep using basic auth or maybe you would like to add some kind of token/session system?

**Comment by n1try** [comment]
No worries.
I'd stick with basic auth for now. Sessions could be added later.
