### ISSUE TITLE
multiple-value uuid.NewV4() in single-value contex

### ISSUE THREAD

**Issue by ronilaukkarinen** [n1try/wakapi#14]
Hello,

In both Fedora 31 and macOS 10.15.3 I get following:

```
~ go get github.com/n1try/wakapi

# github.com/n1try/wakapi
../go/src/github.com/n1try/wakapi/main.go:200:22: multiple-value uuid.NewV4() in single-value contex
```

What gives?

**Comment by n1try** [comment]
Thanks for the report. I'm going to take a look into this later. Hold on.

**Comment by n1try** [comment]
Alright, so here's how to fix your problem.
Before running `go get github.com/n1try/wakapi` please first do `export GO111MODULE=on`.
I'm going to update the Readme accordingly.
Please let me know if that fixed the issue for you.

**Comment by ronilaukkarinen** [comment]
It works now, thanks!
